language: ruby
before_script: 
  - "sudo apt-get update && sudo apt-get install -qq ffmpeg"
  - "bundle exec rackup features/support/config.ru &"
rvm:
  - 2.0.0
  - 1.9.3
  - 2.1.2
  - jruby-head
  - jruby-19mode
  - rbx-2.2.3
matrix:
  allow_failures:
    - rvm: jruby-head
    - rvm: jruby-19mode
    - rvm: rbx-2.2.3
