language: ruby
before_script: "sudo apt-get install -qq ffmpeg"
rvm:
  - 2.0.0
  - 1.9.3
  - allow_failures:
    - 2.1.0
matrix:
  allow_failures:
    - rvm: 2.1.0
    - rvm: jruby-head
    - rvm: jruby-19mode
    - rvm: rbx-19mode
