sudo: required
dist: xenial
language: ruby
before_script: 
# Ubuntu 12.4:  - "sudo apt-get update && sudo apt-get install -qq ffmpeg"
  - "sudo apt-get install -qq libav-tools" # && sudo ln /usr/bin/avconv /usr/bin/ffmpeg"
  - "bundle exec rackup features/support/config.ru &"
rvm:
  - 2.5.3
  - 2.6.0
  - 3.0.0
matrix:
  allow_failures:
    - rvm: 2.6.0
    - rvm: 3.0.0
