language: ruby
before_script: 
  - "sudo apt-get update && sudo apt-get install -qq ffmpeg"
# Ubuntu 14.4:  - "sudo apt-get install -qq libav-tools && sudo ln /usr/bin/avconv /usr/bin/ffmpeg"
  - "bundle exec rackup features/support/config.ru &"
rvm:
  - 2.0.0
  - 1.9.3
  - 2.1.5
  - 2.2.3
matrix:
  allow_failures:
    - rvm: 1.9.3
